steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-eu01
    integrationFlowId: cdflow-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-eu01
    integrationFlowId: cdflow-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-eu01
    integrationFlowId: cdflow-flow4
    integrationFlowName: cdflow-flow4
    packageId: CICD
    filePath: cdflow-flow4.zip